version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 rm --recursive s3://$S3_BUCKET
      - aws s3 cp ./docs/.vuepress/dist s3://$S3_BUCKET --recursive
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
