site_name: 0x4447, LLC. - Documentation
site_url: https://documentation.0x4447.com
repo_url: https://github.com/0x4447-office/0x4447_webpage_documentation
site_author: '0x4447, LLC.'

copyright: 'Est. 2016, Copr. <a href="https://0x4447.com">0x4447, LLC.</a>'

use_directory_urls: false

nav:
    - Home: index.md
    - Products:
      - Cloud:
        - AWS Marketplace:
          - OpenVPN Server: products/cloud/aws-marketplace/openvpn-server.md
          - Rsyslog Server: products/cloud/aws-marketplace/rsyslog-server.md
          - Samba Server: products/cloud/aws-marketplace/samba-server.md
          - SFTP Single User Server: products/cloud/aws-marketplace/sftp-single-user-server.md
