site_name: 0x4447, LLC. - Documentation
site_url: https://documentation.0x4447.com
repo_url: https://github.com/0x4447-office/0x4447_webpage_documentation
site_author: '0x4447, LLC.'

copyright: 'Est. 2016, Copr. <a href="https://0x4447.com">0x4447, LLC.</a>'

use_directory_urls: false

nav:
    - Home: index.md
    - Products:
      - Cloud:
        - AWS Marketplace:
          - Rsyslog Server: products/cloud/aws-marketplace/rsyslog-server.md
          - OpenVPN Server: products/cloud/aws-marketplace/openvpn-server.md
        - Azure:
          - Rsyslog Server: products/cloud/azure/rsyslog-server.md
          - OpenVPN Server: products/cloud/azure/openvpn-server.md
      - Hardware:
        - Placeholder: products/hardware/placeholder.md
