site_name: 0x4447, LLC. Documentation
site_url: https://documentation.0x4447.com
repo_url: https://github.com/0x4447-office/0x4447_webpage_documentation
site_description: '0x4447, LLC. Documentation Page for all of our products.'
site_author: '0x4447, LLC.'

copyright: 'Est. 2016, Copr. <a href="https://0x4447.com">0x4447, LLC.</a>'

nav:
    - Home: index.md
    - Products:
      - Rsyslog Server: products/rsyslog-server.md
      - OpenVPN Server: products/openvpn-server.md

use_directory_urls: false